state_size: 240
action_size: 60
k: 10
theta: 2
episodes: 300
time_units_per_episode: 10000
debug: false
logging: false
progress_bar: true
tracking: false
alpha: 1
beta: 1
initial_inventory: 30
lead_time: 1
learning_rate: .8
learning_rate_decay_parameter: 1000000
expiration_time: 4
discount_factor: .9
exploration_rate: 1.0
exploration_decay_parameter: 500000
min_exploration_rate: .1
trajectory_file: "trajectory.csv"
