state_size: 100
action_size: 20
k: 4
theta: 3
episodes: 2000
time_units_per_episode: 100000
debug: false
logging: true
progress_bar: false
alpha: 1
beta: 1
initial_inventory: 10
lead_time: 2
learning_rate: .8
learning_rate_decay_parameter: 100000000
expiration_time: 5
discount_factor: .9
exploration_rate: 1.0
exploration_decay_parameter: 100000000
min_exploration_rate: .0001
trajectory_file: "trajectory.csv"
