state_size: 40
action_size: 20
k: 3
theta: 3
episodes: 250
time_units_per_episode: 100000
debug: false
logging: false
progress_bar: true
tracking: false
alpha: 1
beta: 1
initial_inventory: 10
lead_time: 1
learning_rate: .8
learning_rate_decay_parameter: 1000000
expiration_time: 2
discount_factor: .9
exploration_rate: 1.0
exploration_decay_parameter: 500000
min_exploration_rate: .0001
trajectory_file: "trajectory.csv"
