state_size: 100
action_size: 20
k: 2
theta: 3
episodes: 300
time_units_per_episode: 100000
debug: false
alpha: 1
beta: 1
initial_inventory: 10
lead_time: 1
learning_rate: .1
expiration_time: 2
discount_factor: .9
exploration_rate: .9
exploration_decay: .975
min_exploration_rate: 0
